language: generic
sudo: false
dist: trusty

env:
  global:
    BYOND_MAJOR="513"
    BYOND_MINOR="1505"

# ALL MAPS MUST BE PRESENT HERE
# IF THEY ARE NOT, YOUR BUILD WILL FAIL
  matrix:
    - TEST=CODE
    - TEST=WEB
    #- TEST=MAP MAP_PATH=example
    #- TEST=MAP MAP_PATH=overmap_example
    - TEST=MAP MAP_PATH=operation_trebuchet
    - TEST=MAP MAP_PATH=slayer
    - TEST=MAP MAP_PATH=firefight
    - TEST=MAP MAP_PATH=crusade
    - TEST=MAP MAP_PATH=stranded
    #- TEST=MAP MAP_PATH=unsc_frigate
    - TEST=MAP MAP_PATH=geminus_city
    - TEST=MAP MAP_PATH=first_contact
    - TEST=MAP MAP_PATH=ccs_battlecruiser
    - TEST=MAP MAP_PATH=doisac
    - TEST=MAP MAP_PATH=unsc_achlys

cache:
  directories:
    - tgui/node_modules
    - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}

addons:
  apt:
    packages:
      - libc6-i386
      - libgcc1:i386
      - libstdc++6:i386
      - oracle-java9-set-default

script:
  - travis_wait 20 test/run-test.sh
